enum Color {
    WHITE, RED, ORANGE, BLUE, STAR
};
//if you're on WHITE, you lose
//if you're on STAR, you win

int matrix[12][10] = {
    {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE},
    {WHITE, WHITE, WHITE, WHITE, STAR, WHITE, WHITE, WHITE, WHITE, WHITE},
    {WHITE, WHITE, WHITE, WHITE, RED, WHITE, WHITE, WHITE, WHITE, WHITE},
    {WHITE, ORANGE, RED, RED, ORANGE, WHITE, WHITE, WHITE, WHITE, WHITE},
    {WHITE, RED, ORANGE, RED, RED, RED, RED, RED, ORANGE, WHITE},
    {WHITE, RED, RED, WHITE, RED, WHITE, WHITE, WHITE, RED, WHITE},
    {WHITE, ORANGE, RED, RED, ORANGE, RED, ORANGE, RED, RED, WHITE},
    {WHITE, WHITE, ORANGE, RED, RED, WHITE, RED, WHITE, RED, WHITE},
    {WHITE, WHITE, WHITE, WHITE, ORANGE, RED, RED, RED, ORANGE, WHITE},
    {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, RED, WHITE, WHITE, WHITE},
    {WHITE, WHITE, WHITE, WHITE, WHITE, RED, ORANGE, WHITE, WHITE, WHITE},
    {WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE, WHITE}
};